import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { getDb } from "@/db/client";
import { linkedAccounts, users } from "@/db/schema";
import { ensureMeshlyFolder, getDriveAbout } from "@/lib/google/drive";
import { exchangeGoogleCode, getGoogleProfile, type GoogleMode } from "@/lib/google/oauth";
import { createSessionToken, encryptSecret, verifySessionToken } from "@/lib/security/crypto";

export async function GET(request:NextRequest){const fail=(reason:string)=>NextResponse.redirect(new URL(`/login?error=${encodeURIComponent(reason)}`,request.url));try{const code=request.nextUrl.searchParams.get("code");const returnedState=request.nextUrl.searchParams.get("state");const state=request.cookies.get("meshly_oauth_state")?.value;const verifier=request.cookies.get("meshly_oauth_verifier")?.value;const mode=(request.cookies.get("meshly_oauth_mode")?.value==="full"?"full":"managed") as GoogleMode;if(!code||!state||!verifier||returnedState!==state)return fail("oauth_state_invalid");const tokens=await exchangeGoogleCode(code,verifier);const [profile,about,folderId]=await Promise.all([getGoogleProfile(tokens.access_token),getDriveAbout(tokens.access_token),ensureMeshlyFolder(tokens.access_token)]);const db=getDb();let userId:string|undefined;const existingSession=request.cookies.get("meshly_session")?.value;if(existingSession){try{userId=(await verifySessionToken(existingSession)).userId;}catch{}}
 if(!userId){const existing=await db.select().from(users).where(eq(users.email,profile.email)).limit(1);if(existing[0]){userId=existing[0].id;await db.update(users).set({name:profile.name,avatarUrl:profile.picture,updatedAt:new Date()}).where(eq(users.id,userId));}else{userId=nanoid();await db.insert(users).values({id:userId,email:profile.email,name:profile.name,avatarUrl:profile.picture});}}
 const old=await db.select().from(linkedAccounts).where(and(eq(linkedAccounts.userId,userId),eq(linkedAccounts.googleSubject,profile.sub))).limit(1);const refresh=tokens.refresh_token?encryptSecret(tokens.refresh_token):old[0]?.refreshTokenEncrypted;if(!refresh)return fail("refresh_token_missing");const limit=Number(about.storageQuota?.limit??0);const usage=Number(about.storageQuota?.usage??0);if(old[0])await db.update(linkedAccounts).set({email:profile.email,name:profile.name,avatarUrl:profile.picture,mode,refreshTokenEncrypted:refresh,storageFolderId:folderId,quotaLimit:limit,quotaUsage:usage,status:"healthy",updatedAt:new Date()}).where(eq(linkedAccounts.id,old[0].id));else await db.insert(linkedAccounts).values({id:nanoid(),userId,googleSubject:profile.sub,email:profile.email,name:profile.name,avatarUrl:profile.picture,mode,refreshTokenEncrypted:refresh,storageFolderId:folderId,quotaLimit:limit,quotaUsage:usage});
 const response=NextResponse.redirect(new URL("/accounts?connected=1",request.url));response.cookies.set("meshly_session",await createSessionToken(userId),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:60*60*24*7});for(const name of ["meshly_oauth_state","meshly_oauth_verifier","meshly_oauth_mode"])response.cookies.set(name,"",{path:"/",maxAge:0});return response;}catch(error){console.error("OAuth callback failed",error);return fail("oauth_callback_failed");}}
