CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY,email text NOT NULL UNIQUE,name text,avatar_url text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS linked_accounts (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,google_subject text NOT NULL UNIQUE,email text NOT NULL,name text,avatar_url text,mode text NOT NULL DEFAULT 'managed',refresh_token_encrypted text NOT NULL,storage_folder_id text,quota_limit bigint NOT NULL DEFAULT 0,quota_usage bigint NOT NULL DEFAULT 0,priority integer NOT NULL DEFAULT 100,status text NOT NULL DEFAULT 'healthy',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS linked_accounts_user_idx ON linked_accounts(user_id);
CREATE TABLE IF NOT EXISTS logical_files (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,parent_id text,name text NOT NULL,mime_type text NOT NULL,size bigint NOT NULL,sha256 text,status text NOT NULL DEFAULT 'uploading',starred integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS logical_files_user_parent_idx ON logical_files(user_id,parent_id);
CREATE TABLE IF NOT EXISTS chunks (id text PRIMARY KEY,file_id text NOT NULL REFERENCES logical_files(id) ON DELETE CASCADE,account_id text NOT NULL REFERENCES linked_accounts(id) ON DELETE RESTRICT,part integer NOT NULL,offset bigint NOT NULL,size bigint NOT NULL,physical_name text NOT NULL,drive_file_id text,sha256 text,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(file_id,part));
CREATE INDEX IF NOT EXISTS chunks_account_idx ON chunks(account_id);
CREATE TABLE IF NOT EXISTS activities (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind text NOT NULL,subject_id text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS activities_user_idx ON activities(user_id,created_at DESC);
