import { asc,eq } from "drizzle-orm";
import { getDb } from "@/db/client";
import { chunks,linkedAccounts,logicalFiles } from "@/db/schema";
import { downloadDriveFile } from "@/lib/google/drive";
import { refreshGoogleAccessToken } from "@/lib/google/oauth";
import { decryptSecret } from "@/lib/security/crypto";

function rangeOf(header:string|null,size:number){if(size===0)return{start:0,end:-1,partial:false};if(!header)return{start:0,end:size-1,partial:false};const m=/^bytes=(\d+)-(\d*)$/.exec(header);if(!m)return null;const start=Number(m[1]);const end=m[2]?Number(m[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||end>=size)return null;return{start,end,partial:true};}
export async function streamLogicalFile(fileId:string,rangeHeader:string|null,disposition:"attachment"|"inline"="attachment"){const db=getDb();const file=(await db.select().from(logicalFiles).where(eq(logicalFiles.id,fileId)).limit(1))[0];if(!file||file.status!=="ready"||file.trashedAt)return new Response("Not found",{status:404});if(file.mimeType==="application/vnd.meshly.folder")return new Response("Folders cannot be downloaded directly",{status:400});const requested=rangeOf(rangeHeader,file.size);if(!requested)return new Response("Invalid range",{status:416,headers:{"Content-Range":`bytes */${file.size}`}});const rows=await db.select({chunk:chunks,account:linkedAccounts}).from(chunks).innerJoin(linkedAccounts,eq(chunks.accountId,linkedAccounts.id)).where(eq(chunks.fileId,file.id)).orderBy(asc(chunks.part));const relevant=rows.filter(({chunk})=>chunk.offset<=requested.end&&chunk.offset+chunk.size-1>=requested.start);if(!relevant.length||relevant.some(x=>!x.chunk.driveFileId||x.chunk.status!=="ready"))return new Response("File is incomplete",{status:409});let index=0;let reader:ReadableStreamDefaultReader<Uint8Array>|null=null;const tokenCache=new Map<string,string>();const stream=new ReadableStream<Uint8Array>({async pull(controller){try{while(true){if(reader){const next=await reader.read();if(!next.done){controller.enqueue(next.value);return;}reader=null;index++;}if(index>=relevant.length){controller.close();return;}const {chunk,account}=relevant[index];let access=tokenCache.get(account.id);if(!access){access=await refreshGoogleAccessToken(decryptSecret(account.refreshTokenEncrypted));tokenCache.set(account.id,access);}const localStart=Math.max(requested.start,chunk.offset)-chunk.offset;const localEnd=Math.min(requested.end,chunk.offset+chunk.size-1)-chunk.offset;const response=await downloadDriveFile(access,chunk.driveFileId!,`bytes=${localStart}-${localEnd}`);if(!response.ok||!response.body)throw new Error(`Drive chunk download failed (${response.status})`);reader=response.body.getReader();}}catch(error){controller.error(error);}},cancel(){void reader?.cancel();}});const length=requested.end-requested.start+1;const headers=new Headers({"Content-Type":file.mimeType||"application/octet-stream","Content-Length":String(length),"Accept-Ranges":"bytes","Cache-Control":"private, no-store","Content-Disposition":`${disposition}; filename*=UTF-8''${encodeURIComponent(file.name)}`});if(requested.partial)headers.set("Content-Range",`bytes ${requested.start}-${requested.end}/${file.size}`);return new Response(stream,{status:requested.partial?206:200,headers});}
