import { createHmac } from "node:crypto";
import { eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { getDb } from "@/db/client";
import { activities,chunks,linkedAccounts,logicalFiles,syncState } from "@/db/schema";
import { upsertAppDataFile } from "@/lib/google/drive";
import { refreshGoogleAccessToken } from "@/lib/google/oauth";
import { decryptSecret } from "@/lib/security/crypto";

function recoveryKey(){const key=process.env.RECOVERY_SECRET??process.env.SESSION_SECRET;if(!key)throw new Error("RECOVERY_SECRET or SESSION_SECRET is required");return key;}
export async function buildRecoveryDocument(userId:string){const db=getDb();const [files,parts]=await Promise.all([db.select().from(logicalFiles).where(eq(logicalFiles.userId,userId)),db.select({chunk:chunks}).from(chunks).innerJoin(logicalFiles,eq(chunks.fileId,logicalFiles.id)).where(eq(logicalFiles.userId,userId))]);const payload={version:1,generatedAt:new Date().toISOString(),userId,files:files.map(f=>({id:f.id,parentId:f.parentId,name:f.name,mimeType:f.mimeType,size:f.size,sha256:f.sha256,status:f.status,starred:f.starred,trashedAt:f.trashedAt?.toISOString()??null,trashedParentId:f.trashedParentId,createdAt:f.createdAt.toISOString(),updatedAt:f.updatedAt.toISOString()})),chunks:parts.map(({chunk})=>({id:chunk.id,fileId:chunk.fileId,accountId:chunk.accountId,part:chunk.part,offset:chunk.offset,size:chunk.size,physicalName:chunk.physicalName,driveFileId:chunk.driveFileId,sha256:chunk.sha256,status:chunk.status}))};const serialized=JSON.stringify(payload);const signature=createHmac("sha256",recoveryKey()).update(serialized).digest("base64url");return JSON.stringify({payload,signature});}
export async function writeRecoverySnapshot(userId:string){const db=getDb();const [document,accounts]=await Promise.all([buildRecoveryDocument(userId),db.select().from(linkedAccounts).where(eq(linkedAccounts.userId,userId))]);let written=0;const failures:string[]=[];for(const account of accounts.filter(a=>a.status==="healthy")){try{const access=await refreshGoogleAccessToken(decryptSecret(account.refreshTokenEncrypted));await upsertAppDataFile(access,"meshly-recovery-v1.json",document);await db.insert(syncState).values({accountId:account.id,lastRecoverySnapshot:new Date(),lastError:null}).onConflictDoUpdate({target:syncState.accountId,set:{lastRecoverySnapshot:new Date(),lastError:null,updatedAt:new Date()}});written++;}catch(error){const message=error instanceof Error?error.message:"snapshot failed";failures.push(`${account.email}: ${message}`);await db.insert(syncState).values({accountId:account.id,lastError:message}).onConflictDoUpdate({target:syncState.accountId,set:{lastError:message,updatedAt:new Date()}});}}await db.insert(activities).values({id:nanoid(),userId,kind:"recovery_snapshot",metadata:{written,failures:failures.length}});return{written,failures};}
