export type DriveAbout={user?:{displayName?:string;emailAddress?:string;photoLink?:string};storageQuota?:{limit?:string;usage?:string;usageInDrive?:string;usageInDriveTrash?:string}};
const auth=(accessToken:string)=>({authorization:`Bearer ${accessToken}`});
export async function getDriveAbout(accessToken:string){const fields="user(displayName,emailAddress,photoLink),storageQuota(limit,usage,usageInDrive,usageInDriveTrash)";const response=await fetch(`https://www.googleapis.com/drive/v3/about?fields=${encodeURIComponent(fields)}`,{headers:auth(accessToken),cache:"no-store"});if(!response.ok)throw new Error(`Drive quota request failed (${response.status})`);return response.json() as Promise<DriveAbout>;}
export async function ensureMeshlyFolder(accessToken:string){const q="name='Meshly Storage' and mimeType='application/vnd.google-apps.folder' and trashed=false";const list=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&spaces=drive&fields=files(id,name)&pageSize=10`,{headers:auth(accessToken),cache:"no-store"});if(!list.ok)throw new Error("Unable to inspect Meshly storage folder");const existing=await list.json() as {files?:{id:string}[]};if(existing.files?.[0]?.id)return existing.files[0].id;const create=await fetch("https://www.googleapis.com/drive/v3/files?fields=id",{method:"POST",headers:{...auth(accessToken),"content-type":"application/json"},body:JSON.stringify({name:"Meshly Storage",mimeType:"application/vnd.google-apps.folder",appProperties:{meshly:"storage-root"}})});if(!create.ok)throw new Error("Unable to create Meshly storage folder");return ((await create.json()) as {id:string}).id;}
export async function createResumableSession(accessToken:string,input:{name:string;size:number;mimeType:string;parentId:string;appProperties?:Record<string,string>}){const response=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,size",{method:"POST",headers:{...auth(accessToken),"content-type":"application/json; charset=UTF-8","x-upload-content-type":input.mimeType,"x-upload-content-length":String(input.size)},body:JSON.stringify({name:input.name,parents:[input.parentId],mimeType:input.mimeType,appProperties:input.appProperties??{}})});if(!response.ok)throw new Error(`Unable to start Drive upload (${response.status})`);const url=response.headers.get("location");if(!url)throw new Error("Drive did not return a resumable session URL");return url;}
export async function getDriveFileMetadata(accessToken:string,fileId:string){const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?fields=id,name,size,md5Checksum,sha256Checksum,trashed`,{headers:auth(accessToken),cache:"no-store"});if(!response.ok)throw new Error(`Unable to verify Drive file (${response.status})`);return response.json() as Promise<{id:string;name:string;size?:string;md5Checksum?:string;sha256Checksum?:string;trashed?:boolean}>;}
export async function downloadDriveFile(accessToken:string,fileId:string,range?:string){return fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?alt=media`,{headers:{...auth(accessToken),...(range?{range}:{})},cache:"no-store"});}
export async function deleteDriveFile(accessToken:string,fileId:string){const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}`,{method:"DELETE",headers:auth(accessToken),cache:"no-store"});if(!response.ok&&response.status!==404)throw new Error(`Unable to delete Drive file (${response.status})`);}
export async function findAppDataFile(accessToken:string,name:string){const q=`name='${name.replaceAll("'","\\'")}' and trashed=false`;const response=await fetch(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${encodeURIComponent(q)}&fields=files(id,name,modifiedTime)&pageSize=10`,{headers:auth(accessToken),cache:"no-store"});if(!response.ok)throw new Error(`Unable to inspect appDataFolder (${response.status})`);const data=await response.json() as {files?:{id:string;name:string;modifiedTime?:string}[]};return data.files?.[0]??null;}
export async function upsertAppDataFile(accessToken:string,name:string,content:string){let existing=await findAppDataFile(accessToken,name);if(!existing){const created=await fetch("https://www.googleapis.com/drive/v3/files?fields=id",{method:"POST",headers:{...auth(accessToken),"content-type":"application/json"},body:JSON.stringify({name,parents:["appDataFolder"],mimeType:"application/json"}),cache:"no-store"});if(!created.ok)throw new Error(`Unable to create appData file (${created.status})`);existing=await created.json() as {id:string;name:string};}const upload=await fetch(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(existing.id)}?uploadType=media`,{method:"PATCH",headers:{...auth(accessToken),"content-type":"application/json; charset=UTF-8"},body:content,cache:"no-store"});if(!upload.ok)throw new Error(`Unable to update appData file (${upload.status})`);return existing.id;}
