import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { getDb } from "@/db/client";
import { chunks, linkedAccounts, logicalFiles } from "@/db/schema";
import { createResumableSession, ensureMeshlyFolder } from "@/lib/google/drive";
import { refreshGoogleAccessToken } from "@/lib/google/oauth";
import { decryptSecret, verifySessionToken } from "@/lib/security/crypto";
import { planPlacement } from "@/lib/storage/planner";

const inputSchema=z.object({name:z.string().min(1).max(255),size:z.number().int().positive().max(5*1024*1024*1024*1024),mimeType:z.string().min(1).max(200).default("application/octet-stream"),parentId:z.string().nullable().optional()});
export async function POST(request:NextRequest){try{const session=request.cookies.get("meshly_session")?.value;if(!session)return NextResponse.json({error:"unauthorized"},{status:401});const {userId}=await verifySessionToken(session);const input=inputSchema.parse(await request.json());const db=getDb();const accounts=await db.select().from(linkedAccounts).where(and(eq(linkedAccounts.userId,userId),eq(linkedAccounts.status,"healthy")));const placements=planPlacement(input.size,accounts.map(a=>({id:a.id,freeBytes:Math.max(0,a.quotaLimit-a.quotaUsage),priority:a.priority,healthy:a.status==="healthy"})));const fileId=nanoid();await db.insert(logicalFiles).values({id:fileId,userId,parentId:input.parentId??null,name:input.name,mimeType:input.mimeType,size:input.size,status:"uploading"});const sessions=[];for(const placement of placements){const account=accounts.find(a=>a.id===placement.accountId);if(!account)throw new Error("Storage account disappeared during planning");const accessToken=await refreshGoogleAccessToken(decryptSecret(account.refreshTokenEncrypted));const parentId=account.storageFolderId??await ensureMeshlyFolder(accessToken);if(!account.storageFolderId)await db.update(linkedAccounts).set({storageFolderId:parentId}).where(eq(linkedAccounts.id,account.id));const chunkId=nanoid();const physicalName=`.meshly-${fileId}.part-${String(placement.part).padStart(4,"0")}`;await db.insert(chunks).values({id:chunkId,fileId,accountId:account.id,part:placement.part,offset:placement.offset,size:placement.size,physicalName});const uploadUrl=await createResumableSession(accessToken,{name:physicalName,size:placement.size,mimeType:"application/octet-stream",parentId,appProperties:{meshlyFileId:fileId,meshlyChunkId:chunkId,meshlyPart:String(placement.part)}});sessions.push({chunkId,accountId:account.id,part:placement.part,offset:placement.offset,size:placement.size,uploadUrl});}return NextResponse.json({fileId,sessions});}catch(error){console.error("Upload planning failed",error);const message=error instanceof Error?error.message:"Unable to plan upload";return NextResponse.json({error:message},{status:message.includes("enough pooled")?507:400});}}
