"use client";
import { createSHA256 } from "hash-wasm";

type PlannedSession={chunkId:string;accountId:string;part:number;offset:number;size:number;uploadUrl:string};
type PlanResponse={fileId:string;sessions:PlannedSession[]};
const NETWORK_CHUNK=8*1024*1024;

async function hashSlice(file:File,start:number,size:number,whole?:Awaited<ReturnType<typeof createSHA256>>){const hasher=await createSHA256();hasher.init();let cursor=0;while(cursor<size){const end=Math.min(cursor+NETWORK_CHUNK,size);const bytes=new Uint8Array(await file.slice(start+cursor,start+end).arrayBuffer());hasher.update(bytes);whole?.update(bytes);cursor=end;}return hasher.digest("hex");}
async function putResumable(session:PlannedSession,file:File,onBytes:(n:number)=>void){let cursor=0;let driveFileId="";while(cursor<session.size){const end=Math.min(cursor+NETWORK_CHUNK,session.size);const body=file.slice(session.offset+cursor,session.offset+end);let response:Response|undefined;for(let attempt=0;attempt<4;attempt++){response=await fetch(session.uploadUrl,{method:"PUT",headers:{"Content-Range":`bytes ${cursor}-${end-1}/${session.size}`},body});if(response.status===308||response.ok)break;if(response.status>=500)await new Promise(r=>setTimeout(r,500*Math.pow(2,attempt)));else break;}if(!response||(!response.ok&&response.status!==308))throw new Error(`Upload part ${session.part+1} failed (${response?.status??"network"})`);onBytes(end-cursor);cursor=end;if(response.ok){const data=await response.json() as {id?:string};driveFileId=data.id??"";}}if(!driveFileId)throw new Error(`Drive did not finalize part ${session.part+1}`);return driveFileId;}

export async function uploadMeshlyFile(file:File,onProgress?:(value:{phase:"planning"|"hashing"|"uploading"|"verifying"|"done";percent:number;part?:number;parts?:number})=>void){onProgress?.({phase:"planning",percent:0});const planResponse=await fetch("/api/uploads/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:file.name,size:file.size,mimeType:file.type||"application/octet-stream"})});if(!planResponse.ok){const data=await planResponse.json().catch(()=>({}));throw new Error(data.error??"Unable to plan upload");}const plan=await planResponse.json() as PlanResponse;const whole=await createSHA256();whole.init();const hashes=new Map<string,string>();let hashed=0;for(const session of plan.sessions){const hash=await hashSlice(file,session.offset,session.size,whole);hashes.set(session.chunkId,hash);hashed+=session.size;onProgress?.({phase:"hashing",percent:Math.round((hashed/file.size)*100),part:session.part+1,parts:plan.sessions.length});}const wholeHash=whole.digest("hex");let uploaded=0;const completed=[];for(const session of plan.sessions){const driveFileId=await putResumable(session,file,n=>{uploaded+=n;onProgress?.({phase:"uploading",percent:Math.min(100,Math.round((uploaded/file.size)*100)),part:session.part+1,parts:plan.sessions.length});});completed.push({chunkId:session.chunkId,driveFileId,sha256:hashes.get(session.chunkId)!});}onProgress?.({phase:"verifying",percent:100,parts:plan.sessions.length});const commit=await fetch("/api/uploads/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileId:plan.fileId,sha256:wholeHash,chunks:completed})});if(!commit.ok)throw new Error("Remote verification failed");onProgress?.({phase:"done",percent:100,parts:plan.sessions.length});return commit.json() as Promise<{ok:true;fileId:string;downloadUrl:string}>;}
