import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db/client";
import { chunks, linkedAccounts, logicalFiles } from "@/db/schema";
import { getDriveFileMetadata } from "@/lib/google/drive";
import { refreshGoogleAccessToken } from "@/lib/google/oauth";
import { decryptSecret, verifySessionToken } from "@/lib/security/crypto";

const schema=z.object({fileId:z.string().min(1),sha256:z.string().regex(/^[a-f0-9]{64}$/i),chunks:z.array(z.object({chunkId:z.string().min(1),driveFileId:z.string().min(1),sha256:z.string().regex(/^[a-f0-9]{64}$/i)})).min(1)});
export async function POST(request:NextRequest){try{const session=request.cookies.get("meshly_session")?.value;if(!session)return NextResponse.json({error:"unauthorized"},{status:401});const {userId}=await verifySessionToken(session);const input=schema.parse(await request.json());const db=getDb();const file=(await db.select().from(logicalFiles).where(and(eq(logicalFiles.id,input.fileId),eq(logicalFiles.userId,userId))).limit(1))[0];if(!file)return NextResponse.json({error:"file_not_found"},{status:404});const stored=await db.select().from(chunks).where(eq(chunks.fileId,file.id));if(stored.length!==input.chunks.length)return NextResponse.json({error:"chunk_count_mismatch"},{status:409});for(const submitted of input.chunks){const chunk=stored.find(c=>c.id===submitted.chunkId);if(!chunk)return NextResponse.json({error:"unknown_chunk"},{status:409});const account=(await db.select().from(linkedAccounts).where(and(eq(linkedAccounts.id,chunk.accountId),eq(linkedAccounts.userId,userId))).limit(1))[0];if(!account)throw new Error("Storage account missing");const access=await refreshGoogleAccessToken(decryptSecret(account.refreshTokenEncrypted));const remote=await getDriveFileMetadata(access,submitted.driveFileId);if(remote.trashed||Number(remote.size??-1)!==chunk.size)return NextResponse.json({error:"remote_chunk_verification_failed",chunkId:chunk.id},{status:409});await db.update(chunks).set({driveFileId:submitted.driveFileId,sha256:submitted.sha256,status:"ready"}).where(eq(chunks.id,chunk.id));}await db.update(logicalFiles).set({sha256:input.sha256,status:"ready",updatedAt:new Date()}).where(eq(logicalFiles.id,file.id));return NextResponse.json({ok:true,fileId:file.id,downloadUrl:`/api/files/${file.id}/download`});}catch(error){console.error("Upload commit failed",error);return NextResponse.json({error:"commit_failed"},{status:400});}}
