import { createCipheriv, createDecipheriv, randomBytes, createHash } from "node:crypto";
import { SignJWT, jwtVerify } from "jose";

function key(){const raw=process.env.TOKEN_ENCRYPTION_KEY;if(!raw)throw new Error("TOKEN_ENCRYPTION_KEY is required");const decoded=Buffer.from(raw,"base64");if(decoded.length!==32)throw new Error("TOKEN_ENCRYPTION_KEY must be 32 bytes encoded as base64");return decoded;}
export function encryptSecret(value:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);const tag=cipher.getAuthTag();return ["v1",iv.toString("base64url"),tag.toString("base64url"),encrypted.toString("base64url")].join(".");}
export function decryptSecret(value:string){const [version,iv,tag,data]=value.split(".");if(version!=="v1"||!iv||!tag||!data)throw new Error("Invalid encrypted secret");const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8");}
function sessionKey(){const raw=process.env.SESSION_SECRET;if(!raw)throw new Error("SESSION_SECRET is required");return new TextEncoder().encode(createHash("sha256").update(raw).digest("hex"));}
export async function createSessionToken(userId:string){return new SignJWT({uid:userId}).setProtectedHeader({alg:"HS256"}).setIssuer("meshly").setAudience("meshly-web").setIssuedAt().setExpirationTime("7d").sign(sessionKey());}
export async function verifySessionToken(token:string){const {payload}=await jwtVerify(token,sessionKey(),{issuer:"meshly",audience:"meshly-web"});if(typeof payload.uid!=="string")throw new Error("Invalid session");return {userId:payload.uid};}
