import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

export function createShareToken(){return randomBytes(24).toString("base64url");}
export function hashShareToken(token:string){return createHash("sha256").update(token).digest("hex");}
export function hashSharePassword(password:string){const salt=randomBytes(16);const digest=scryptSync(password,salt,32);return `s1.${salt.toString("base64url")}.${digest.toString("base64url")}`;}
export function verifySharePassword(password:string,stored:string){const [version,saltRaw,digestRaw]=stored.split(".");if(version!=="s1"||!saltRaw||!digestRaw)return false;const expected=Buffer.from(digestRaw,"base64url");const actual=scryptSync(password,Buffer.from(saltRaw,"base64url"),expected.length);return actual.length===expected.length&&timingSafeEqual(actual,expected);}
function grantKey(){const value=process.env.SHARE_GRANT_SECRET??process.env.SESSION_SECRET;if(!value)throw new Error("SHARE_GRANT_SECRET or SESSION_SECRET is required");return value;}
export function createShareGrant(shareId:string,ttlSeconds=900){const payload=Buffer.from(JSON.stringify({shareId,exp:Math.floor(Date.now()/1000)+ttlSeconds})).toString("base64url");const sig=createHmac("sha256",grantKey()).update(payload).digest("base64url");return `${payload}.${sig}`;}
export function verifyShareGrant(token:string|undefined,shareId:string){if(!token)return false;const [payload,sig]=token.split(".");if(!payload||!sig)return false;const expected=createHmac("sha256",grantKey()).update(payload).digest();const actual=Buffer.from(sig,"base64url");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return false;try{const parsed=JSON.parse(Buffer.from(payload,"base64url").toString("utf8")) as {shareId?:string;exp?:number};return parsed.shareId===shareId&&typeof parsed.exp==="number"&&parsed.exp>=Math.floor(Date.now()/1000);}catch{return false;}}
